version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn build

  test:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: large
    working_directory: ~/repo
    environment:
      BASH_ENV: "/opt/circleci/.nvm/nvm.sh"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Install node@v16.13.0
          command: |
            nvm install 16.13.0
            nvm use 16.13.0
            npm install -g yarn
      - run: yarn install
      - run: yarn build
      - run: yarn test

  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - run:
          name: prepare authentication config
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > /home/circleci/project/.npmrc
      - run:
          name: Update tag
          command: npm --no-git-tag-version version $CIRCLE_TAG
      - run:
          name: Publish package
          command: npm publish

no-tags: &no-tags
  filters:
    tags:
      ignore: /.*/

only-release-tags: &only-release-tags
  filters:
    tags:
      only: /^v[0-9]+(\.[0-9]+)*/
    branches:
      ignore: /.*/

workflows:
  version: 2

  default:
    jobs:
      - build:
          <<: *no-tags
      - test:
          <<: *no-tags

  release:
    jobs:
      - build:
          <<: *only-release-tags
      - test:
          <<: *only-release-tags
      - publish:
          <<: *only-release-tags
          requires:
            - build
            - test
